# Configuration de la base de données
quarkus.datasource.db-kind=h2
quarkus.datasource.username=username
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# Configuration Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# --- Securité ---
# Désactivation de l'authentification HTTP Basic de Quarkus
# car l'application gère l'authentification via AuthService (Base de données)
quarkus.security.users.file.enabled=false
quarkus.security.basic.enabled=false

# Enable Virtual Threads (Project Loom)
quarkus.threading.virtual.enabled=true

# Configuration des logs
quarkus.log.level=INFO
quarkus.log.category."com.intermarche".level=DEBUG
quarkus.log.category."stdout".level=INFO

# Configuration de la console
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=DEBUG

# Optimisation Hibernate
quarkus.hibernate-orm.jdbc.batch_size=1000
quarkus.hibernate-orm.jdbc.order_inserts=true
quarkus.hibernate-orm.jdbc.order_updates=true

# CORS
quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/

# --- Configuration du client Hardware (Mock) ---
%dev.quarkus.rest-client.hardware-api.url=http://localhost:8080

# --- Patterns de reconnaissance des codes scannés ---
# Badge Employé : 8 chiffres exactement
scan.pattern.badge=^\\d{8}$
scan.pattern.fidelity=^789\\d{12}$